/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PayWithLn {
    'paymentRequest': string;
  }
  interface PayWithLnAttributes extends StencilHTMLAttributes {
    'paymentRequest'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PayWithLn': Components.PayWithLn;
  }

  interface StencilIntrinsicElements {
    'pay-with-ln': Components.PayWithLnAttributes;
  }


  interface HTMLPayWithLnElement extends Components.PayWithLn, HTMLStencilElement {}
  var HTMLPayWithLnElement: {
    prototype: HTMLPayWithLnElement;
    new (): HTMLPayWithLnElement;
  };

  interface HTMLElementTagNameMap {
    'pay-with-ln': HTMLPayWithLnElement
  }

  interface ElementTagNameMap {
    'pay-with-ln': HTMLPayWithLnElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
